### ISSUE TITLE
Broken with python 3.7

### ISSUE THREAD

**Issue by cloudeigh** [daboross/screeps-starter-python#14]
Async has become a keyword with python 3.7, which breaks Transcrypt 

https://github.com/QQuick/Transcrypt/issues/543

**Comment by daboross** [comment]
Since Transcrypt has released support, it's on us to update.

There are some modifications I made to Transcrypt when I started this project at https://github.com/daboross/transcrypt which may or may not still be necessary. Most of it's removing code that's not necessary when running only on node.js and not in the browser.

I'll look into what changes still need to be made, apply them to the recent Transcrypt release, and update the `requirements.txt` file in this repository with the new modifications release.

**Comment by daboross** [comment]
This is fixed as of #33.
