### ISSUE TITLE
List manipulation doesn't translate right

### ISSUE THREAD

**Issue by TopStreamsNet** [daboross/screeps-starter-python#2]
In python:
```
>>> q=[1,2,3]
>>> y=[4,5]
>>> z=q+4*y
>>> z
[1, 2, 3, 4, 5, 4, 5, 4, 5, 4, 5]
```
Above translated via transcrypt:
```
var q = list ([1, 2, 3]);
var y = list ([4, 5]);
var z = q + 4 * y;
console.log (z);
1,2,3NaN
```

So array manipulation doesn't translate right

**Comment by daboross** [comment]
Yes, this is a known limitation of transcrypt. It's possible to enable operator overloading for lists, etc. with the `--opov` flag, but this will lead to greatly reduced performance.

The problem is that JavaScript does not support custom multiplication or addition per-type, and only supports the operations with integers and strings (as you can see). In order to add support for python list concatenation and multiplication, Transcrypt would replace every `+` or `*` with a function call checking types. This is disabled by default due to the large performance penalty incurred for every operation.

**Comment by TopStreamsNet** [comment]
Ok, I guess I can close this then if this is a known thing. Thanks for the explanation!
