### ISSUE TITLE
Incorrect converting of "for" list iterator

### ISSUE THREAD

**Issue by tvardero** [daboross/screeps-starter-python#29]
```
for _creep in Game.creeps:
    do_something ( _creep )
```
is translated to JS like this:
```
for (var _creep of Game.creeps) {
    do_something ( _creep );
}
```
which raises an error on screeps game console :
```
TypeError: Game.creeps is not iterable
```

Changing "_creep of Game.creeps " to "_creep in Game.creeps" fixes the error. 

Dunno how

**Comment by daboross** [comment]
`of` is the correct usage here, the problem is that `Game.creeps` isn't iterable - and in general, objects are not iterable.

The `in` list would work for this case, but it doesn't translate well in general. For instance, when using `for in` on an array, you end up iterating over the array's indices, while the Python code for iterating over a list usually expects to get that list's values. For more information, see [for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) and [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) MDN pages.

There is no single concept in JavaScript which matches Python's. `for of` was chosen rather than `for in` because it works in many, many more locations than `for in` does. See the screeps-starter-python book for more information on this: https://daboross.gitbook.io/screeps-starter-python/syntax-changes/object-iteration.

With this in mind, the solution is to change the Python code so that you iterate over something iterable, not an object.

To iterate over keys, use

```python
for _creep in Object.keys(Game.creeps):
    do_something ( _creep )
```

To iterate over values:

```python
for _creep in Object.values(Game.creeps):
    do_something ( _creep )
```
