### ISSUE TITLE
Fake classes constructor suggestion

### ISSUE THREAD

**Issue by nicktime** [daboross/screeps-starter-python#3]
`- None of the constructors for game objects are accurate. It's not reliable to create these in game,
  but a 'fake' constructor with all attributes as arguments is created to give type checkers correct
  thoughts on what properties should exist.`

Adding `assert False, 'with some message'` or `raise NotImplementedError('with some message')` to constructors would prevent people from misusing them.

**Comment by daboross** [comment]
I definitely agree with this sentiment - these fake constructors are a bit misleading. They were the best way I could find to inform autocomplete / typing systems what fields exist, but it's true that they don't exist.

I don't think that asserting false or raising an error would fix this though - they're meant to be shells anyways: none of the code in src/defs is included in the transcrypted JavaScript. I could see adding some large warning comments to them to warn not to use them, but raising an error would only help for when looking at the classes, and it might not be obvious that the error is actually warning something (as opposed to just being a NotImplementedError because these are Python stubs for JS functions).

**Comment by daboross** [comment]
I've added some warning comments to all the __init__ methods, let me know if this seems alright.

I'm thinking comments are more effective than raising an error mainly because they're shown in IDEs when using constructors and because errors could be ambiguous.

**Comment by nicktime** [comment]
Ah, yes, you're right, they don't get a chance to run natively.
