### ISSUE TITLE
Link to enviroment setup doesn't work.

### ISSUE THREAD

**Issue by Sycend** [daboross/screeps-starter-python#30]
Link to the Enviroment setup doesn't work in the readme, so does the others link don't work anymore.
Also is this repo still working with the current screeps version?

**Comment by daboross** [comment]
I think the link to setup should now be https://daboross.gitbook.io/screeps-starter-python/overview/setup.

The repo still technically works, but it'll be missing some autocomplete definitions for the newer features - see #27. It also requires an outdated version of Python 3, so that may or may not be a problem depending on your system.
