### ISSUE TITLE
fails to transcrypt

### ISSUE THREAD

**Issue by nicktime** [daboross/screeps-starter-python#4]
```
$ ./build.py 
running transcrypt...

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.54
Copyright (C) Geatec Engineering. License: Apache 2.0


Error while compiling (offending file last):
        File '/s/var/code/screeps-starter-python/src/main.py', line 1, at import of:
        File '/s/var/code/screeps-starter-python/src/harvester.py', line 1, at import of:
        File '/s/var/code/screeps-starter-python/src/defs/__init__.py', line 22, at import of:
        File '/s/var/code/screeps-starter-python/env/lib/python3.6/site-packages/transcrypt/modules/org/transcrypt/stubs/browser.py', line 1, namely:

        Attempt to import module: builtins
        Can't find any of:
                /s/var/code/screeps-starter-python/src/builtins.py
                /s/var/code/screeps-starter-python/src/__javascript__/builtins.mod.js
                /s/var/code/screeps-starter-python/env/lib/python3.6/site-packages/transcrypt/modules/builtins.py
                /s/var/code/screeps-starter-python/env/lib/python3.6/site-packages/transcrypt/modules/__javascript__/builtins.mod.js
                /s/var/code/screeps-starter-python/env/bin/builtins.py
                /s/var/code/screeps-starter-python/env/bin/__javascript__/builtins.mod.js
                /s/var/code/screeps-starter-python/env/lib/python36.zip/builtins.py
                /s/var/code/screeps-starter-python/env/lib/python36.zip/__javascript__/builtins.mod.js
                /s/var/code/screeps-starter-python/env/lib/python3.6/builtins.py
                /s/var/code/screeps-starter-python/env/lib/python3.6/__javascript__/builtins.mod.js
                /s/var/code/screeps-starter-python/env/lib/python3.6/lib-dynload/builtins.py
                /s/var/code/screeps-starter-python/env/lib/python3.6/lib-dynload/__javascript__/builtins.mod.js
                /usr/lib/python3.6/builtins.py
                /usr/lib/python3.6/__javascript__/builtins.mod.js
                /s/var/code/screeps-starter-python/env/lib/python3.6/site-packages/builtins.py
                /s/var/code/screeps-starter-python/env/lib/python3.6/site-packages/__javascript__/builtins.mod.js
                /usr/local/lib/python3.6/dist-packages/builtins.py
                /usr/local/lib/python3.6/dist-packages/__javascript__/builtins.mod.js
                /usr/lib/python3/dist-packages/builtins.py
                /usr/lib/python3/dist-packages/__javascript__/builtins.mod.js


Aborted
Traceback (most recent call last):
  File "./build.py", line 309, in <module>
    main()
  File "./build.py", line 304, in main
    build(config)
  File "./build.py", line 182, in build
    run_transcrypt(config)
  File "./build.py", line 143, in run_transcrypt
    .format(ret, "' '".join(args), source_dir))
Exception: transcrypt failed. exit code: 5. command line '/s/var/code/screeps-starter-python/env/bin/transcrypt' '-n' '-p' '.none' '-b' '/s/var/code/screeps-starter-python/src/main.py'. working dir: '/s/var/code/screeps-starter-python/src'.
```
I guess it's because Transcrypt tries to translate
```
if TYPE_CHECKING:
    from transcrypt.modules.org.transcrypt.stubs.browser import __pragma__
```
So I would just do 
```
# __pragma__('skip')
from transcrypt.modules.org.transcrypt.stubs.browser import __pragma__
```

PS I hope to make a PR a bit later :)

**Comment by daboross** [comment]
Ah yep - sorry for merging these commits without checking them thoroughly! Thank you for catching this.

The code there is definitely relying on Transcrypt removing code in an `if TYPE_CHECKING:` block, which it does not do. I'll revert that part of the typings update.

**Comment by daboross** [comment]
Hoping that fixes it - if not feel free to comment.

Just wanted to get a fix out asap, since this is pretty broken.

**Comment by daboross** [comment]
some background on this:

I have some more modifications to Transcrypt which I haven't included in this repository, mainly because they're pretty hacky. One of the mods is a very limited compile-time `if` evaluator which treats variables named `TYPE_CHECKING` as `false`, and cuts if statements which are essentially `if false:`. This allows for the intended use of `TYPE_CHECKING`: it's for code which is only useful in type checking, but shouldn't ever be run.

Unfortunately, that modification, and a few others, are pretty hacked together, and aren't consistent (`typing.TYPE_CHECKING` is not found, for example). I'm still on the edge on whether to include those or not in this repository, but for now I guess it's better not to.

**Comment by nicktime** [comment]
Ok, thanks, no problem.
I see you have quite a lot of improvements to Transcrypt. Did you try to propose non-hacky patches upstream?

**Comment by daboross** [comment]
I have submitted a number of the patches upstream, but not all of them. More of what I've done could definitely be sent upstream, but I'm hesitant because what's left is either dependent on node.js / Screeps, or a trade-off which I think is useful for screeps, but maybe not in general.

For instance, in my modifications, `{}` literals in Python are translated to `{}` literals in JS: this has a performance benefit, but the disadvantage of not being able to use `.keys()`, or `.entries()` like you would with a real Python dict.

In general my modifications try to be useful in an environment where you're interacting a lot with JS APIs - and I think Transcrypt itself is more aimed at self-sufficient python programs, where the majority of things you're using have been created in Transcrypted python as well.

There's a full list of the things I've changed (but haven't yet been merged upstream) https://github.com/daboross/Transcrypt/releases/tag/screeps-transcrypt-snapshot-4 if you haven't seen it - some of these could definitely be submitted as PRs to QQuick/Transcrypt.
